name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish backend
        run: |
          cd ./monitoring-server
          sbt "gateway/docker:publish"
          sbt "session/docker:publish"
          sbt "equipment/docker:publish"
          sbt "documentation/docker:publish"
          sbt "monitoring/docker:publish"
          sbt "generator/docker:publish"
          sbt "reporting/docker:publish"

      - name: Build and publish backend
        run: |
          cd ./monitoring-client
          docker build . -t qwerheh/monitoring-client:latest
          docker push qwerheh/monitoring-client

      - name: Copy docker-compose.yml to AWS via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PASSWORD }}
          source: "./monitoring-server/docker-compose.yml"
          target: "/home/ubuntu/"

      - name: docker-compose in AWS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            cd ./monitoring-server
            sudo docker-compose down
            sudo docker-compose up -d
