name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Publish Docker images
        run: |
          cd ./monitoring-server
          sbt "gateway/docker:publish"
          sbt "session/docker:publish"
          sbt "equipment/docker:publish"
          sbt "documentation/docker:publish"
          sbt "monitoring/docker:publish"
          sbt "generator/docker:publish"
          sbt "reporting/docker:publish"
