name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Publish XYZ Docker image
        run: |
          sbt gateway/docker:publish
          sbt session/docker:publish
          sbt equipment/docker:publish
          sbt documentation/docker:publish
          sbt monitoring/docker:publish
          sbt generator/docker:publish
          sbt reporting/docker:publish
